// Code generated by "stringer -type=EmitStrategy"; DO NOT EDIT.

package ssevents

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EmitStrategyBlock-0]
	_ = x[EmitStrategyDrop-1]
	_ = x[EmitStrategyTimeout-2]
}

const _EmitStrategy_name = "EmitStrategyBlockEmitStrategyDropEmitStrategyTimeout"

var _EmitStrategy_index = [...]uint8{0, 17, 33, 52}

func (i EmitStrategy) String() string {
	if i < 0 || i >= EmitStrategy(len(_EmitStrategy_index)-1) {
		return "EmitStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EmitStrategy_name[_EmitStrategy_index[i]:_EmitStrategy_index[i+1]]
}
